# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-13 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessinfo',
            name='join_setting',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessinfo',
            name='num_people',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessinfo',
            name='time',
            field=models.IntegerField(),
        ),
    ]
