# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-13 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191013_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessinfo',
            name='time',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
